# Generated by Django 5.0.14 on 2026-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.CharField(blank=True, help_text='e.g. Python, Graphic Design, Tutoring', max_length=255),
        ),
    ]
